# The URL the site will be built for
base_url = "https://iris.best"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Set theme
theme = "DeepThought"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
navbar_items = [
 { code = "en", nav_items = [
  { url = "$BASE_URL/", name = "Home" },
 ]},
]

# Add links to favicon, you can use https://realfavicongenerator.net/ to generate favicon for your site
[extra.favicon]
favicon_16x16 = "/icons/favicon-16x16.png"
favicon_32x32 = "/icons/favicon-32x32.png"
apple_touch_icon = "/icons/apple-touch-icon.png"
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = "Iris Hoffmeyer"
avatar = "/images/me.jpg"

# Social links
[extra.social]
email = "hi@iris.best"
github = "Arzte"
gitlab = "Arzte_Dev"
keybase = "the_doctors_life"
linkedin = "arzte"
stackoverflow = "21725699"
instagram = "frigid_rainbow"
mastodon = "Arzte"
mastodon_server = "witches.live"


# To add google analytics
[extra.analytics]
google = "G-YZRQCK5M0M"
